name: Build & Test

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Zig
        uses: mlugg/setup-zig@v2
      - run: zig build --summary all
      - run: zig build test --summary all
