name: Build & Test

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Homebrew
        uses: homebrew/actions/setup-homebrew@master
      - name: Fetch minimum Zig version
        id: zig-version
        run: |
          ZIG_VER="$(sed -n 's/.*minimum_zig_version = "\([0-9]*\.[0-9]*\)\.[0-9]*".*/\1/p' build.zig.zon)"
          echo "Minimum Zig version: $ZIG_VER"
          echo "version=$ZIG_VER" >> "$GITHUB_OUTPUT"
      - name: Set up Zig
        run: brew install zig@${{ steps.zig-version.outputs.version }}
      - run: zig build vlmzsd vlmzs --summary all
      - run: zig build kmdconv --summary all
      - run: zig build test --summary all
      - run: ./zig-out/bin/vlmzsd --version
      - run: ./zig-out/bin/vlmzs --version
