name: Build & Test

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: mogeko/setup-zig@v1
      - run: zig build vlmzsd vlmzs kmdconv --summary all
      - run: zig build test --summary all
      - run: ./zig-out/bin/vlmzsd --version
      - run: ./zig-out/bin/vlmzs --version
