name: Release

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    paths: ["./Dockerfile"]
  workflow_dispatch:

jobs:
  container:
    name: Build & Push Container Image
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        docker.io/mogeko/vlmzsd
        ghcr.io/mogeko/vlmzsd
      meta-tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=edge
        type=sha,format=short
      cache: true
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
